name: winter_foodies
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #common
  provider: ^6.0.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15

  #data
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

  #design
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.0
  google_fonts: ^4.0.1
  google_maps_flutter: ^2.2.7
  geolocator: ^9.0.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/naver.png
    - assets/kakao.png
    - assets/google.png
    - assets/splash.png



